<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tb_decision_juridique".
 *
 * @property int $id
 * @property string|null $juge_president
 * @property string|null $tribunal
 * @property string|null $greffier
 * @property string|null $jugement
 * @property string|null $ordonnance
 * @property string|null $acquitement
 * @property string|null $recours
 * @property string|null $duree_peine
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property string|null $created_by
 */
class DecisionJuridique extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tb_decision_juridique';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['jugement', 'ordonnance', 'acquitement', 'recours'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['juge_president', 'tribunal', 'greffier', 'duree_peine', 'created_by'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'juge_president' => Yii::t('app', 'Juge President'),
            'tribunal' => Yii::t('app', 'Tribunal'),
            'greffier' => Yii::t('app', 'Greffier'),
            'jugement' => Yii::t('app', 'Jugement'),
            'ordonnance' => Yii::t('app', 'Ordonnance'),
            'acquitement' => Yii::t('app', 'Acquitement'),
            'recours' => Yii::t('app', 'Recours'),
            'duree_peine' => Yii::t('app', 'Duree Peine'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     * add auto date
     */
    public function beforeSave($insert)
    {
        $user_id  = Yii::$app->user->identity->id;
        if (parent::beforeSave($insert)) {
            if ($insert) { // only on insert
                $this->created_at = date('Y-m-d H:i:s');
                $this->updated_at = date('Y-m-d H:i:s');
                $this->created_by = $user_id;
                return parent::beforeSave($insert); // TODO: Change the autogenerated stub
            }
            $this->updated_at = date('Y-m-d H:i:s');
            return true;
        }
    }
}
