<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tb_employe".
 *
 * @property int $id
 * @property string|null $matricule
 * @property string|null $nom
 * @property string|null $prenom
 * @property string|null $postnom
 * @property string|null $date_naissance
 * @property string|null $lieu_naissance
 * @property string|null $date_embauche
 * @property string|null $fonction
 * @property string|null $service
 * @property string|null $prison_name
 * @property string|null $created_by
 * @property string|null $created_at
 * @property string|null $updated_at
 */
class Employe extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tb_employe';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date_naissance', 'date_embauche', 'created_at', 'updated_at'], 'safe'],
            [['matricule'], 'string', 'max' => 16],
            [['nom', 'prenom', 'postnom', 'lieu_naissance', 'fonction', 'service','prison_name', 'created_by'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'matricule' => Yii::t('app', 'Matricule'),
            'nom' => Yii::t('app', 'Nom'),
            'prenom' => Yii::t('app', 'Prenom'),
            'postnom' => Yii::t('app', 'Postnom'),
            'date_naissance' => Yii::t('app', 'Date Naissance'),
            'lieu_naissance' => Yii::t('app', 'Lieu Naissance'),
            'date_embauche' => Yii::t('app', 'Date Embauche'),
            'fonction' => Yii::t('app', 'Fonction'),
            'service' => Yii::t('app', 'Service'),
            'prison_name' => Yii::t('app', 'Prison Name'),
            'created_by' => Yii::t('app', 'Created By'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $user_id  = Yii::$app->user->identity->id;
        if (parent::beforeSave($insert)) {
            if ($insert) { // only on insert
                $this->created_at = date('Y-m-d H:i:s');
                $this->updated_at = date('Y-m-d H:i:s');
                //$this->created_by = $user_id;
                return parent::beforeSave($insert); // TODO: Change the autogenerated stub
            }
            $this->updated_at = date('Y-m-d H:i:s');
            return true;
        }
    }
}
