<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tb_prison_list".
 *
 * @property string $id
 * @property string|null $prison_name
 * @property string|null $location
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property string|null $created_by
 */
class PrisonList extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tb_prison_list';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['id', 'prison_name', 'location', 'created_by'], 'string', 'max' => 255],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'prison_name' => Yii::t('app', 'Prison Name'),
            'location' => Yii::t('app', 'Location'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $user_id  = Yii::$app->user->identity->id;
        if (parent::beforeSave($insert)) {
            if ($insert) { // only on insert
                $this->created_at = date('Y-m-d H:i:s');
                $this->updated_at = date('Y-m-d H:i:s');
                $this->created_by = $user_id;
                return parent::beforeSave($insert); // TODO: Change the autogenerated stub
            }
            $this->updated_at = date('Y-m-d H:i:s');
            return true;
        }
    }
}
