<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tb_stock_alimentaire".
 *
 * @property int $id
 * @property string|null $produit
 * @property int|null $quantite_entre
 * @property int|null $quantite_sorti
 * @property int|null $prix_achat
 * @property string|null $date_achat
 * @property string|null $buy_by
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property int|null $created_by
 */
class StockAlimentaire extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tb_stock_alimentaire';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['quantite_entre', 'quantite_sorti', 'prix_achat', 'created_by'], 'integer'],
            [['date_achat', 'created_at', 'updated_at'], 'safe'],
            [['produit', 'buy_by'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'produit' => Yii::t('app', 'Produit'),
            'quantite_entre' => Yii::t('app', 'Quantite Entre'),
            'quantite_sorti' => Yii::t('app', 'Quantite Sorti'),
            'prix_achat' => Yii::t('app', 'Prix Achat'),
            'date_achat' => Yii::t('app', 'Date Achat'),
            'buy_by' => Yii::t('app', 'Buy By'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $user_id  = Yii::$app->user->identity->id;
        if (parent::beforeSave($insert)) {
            if ($insert) { // only on insert
                $this->created_at = date('Y-m-d H:i:s');
                $this->updated_at = date('Y-m-d H:i:s');
                $this->created_by = $user_id;
                return parent::beforeSave($insert); // TODO: Change the autogenerated stub
            }
            $this->updated_at = date('Y-m-d H:i:s');
            return true;
        }
    }
}
