<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tb_visiteurs".
 *
 * @property int $id
 * @property string|null $vis_noms
 * @property string|null $vis_pris_noms
 * @property string|null $vis_visite_date
 * @property string|null $vis_numero_carte
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property string|null $heure
 * @property string|null $phone
 * @property string|null $adresse
 * @property string|null $picture
 */
class Visiteurs extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tb_visiteurs';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vis_visite_date', 'created_at', 'updated_at', 'heure'], 'safe'],
            [['vis_noms', 'vis_pris_noms', 'vis_numero_carte', 'adresse', 'picture'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 25],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'vis_noms' => Yii::t('app', 'Vis Noms'),
            'vis_pris_noms' => Yii::t('app', 'Vis Pris Noms'),
            'vis_visite_date' => Yii::t('app', 'Vis Visite Date'),
            'vis_numero_carte' => Yii::t('app', 'Vis Numero Carte'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'heure' => Yii::t('app', 'Heure'),
            'phone' => Yii::t('app', 'Phone'),
            'adresse' => Yii::t('app', 'Adresse'),
            'picture' => Yii::t('app', 'Picture'),
        ];
    }


    /**
     * @param bool $insert
     * @return bool
     * this action created now date before save
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) { // only on insert
                $this->created_at = date('Y-m-d H:i:s');
                $this->updated_at = date('Y-m-d H:i:s');
                return parent::beforeSave($insert); // TODO: Change the autogenerated stub
            }
            $this->updated_at = date('Y-m-d H:i:s');
            return true;
        }
    }
}
